// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: config_message.proto

package pb

import (
	_struct "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigMapName      string `protobuf:"bytes,1,opt,name=configMapName,proto3" json:"configMapName,omitempty"`
	ConfigMapNamespace string `protobuf:"bytes,2,opt,name=configMapNamespace,proto3" json:"configMapNamespace,omitempty"`
}

func (x *ConfigMeta) Reset() {
	*x = ConfigMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMeta) ProtoMessage() {}

func (x *ConfigMeta) ProtoReflect() protoreflect.Message {
	mi := &file_config_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMeta.ProtoReflect.Descriptor instead.
func (*ConfigMeta) Descriptor() ([]byte, []int) {
	return file_config_message_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigMeta) GetConfigMapName() string {
	if x != nil {
		return x.ConfigMapName
	}
	return ""
}

func (x *ConfigMeta) GetConfigMapNamespace() string {
	if x != nil {
		return x.ConfigMapNamespace
	}
	return ""
}

type GetWorkerConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigMeta *ConfigMeta `protobuf:"bytes,1,opt,name=configMeta,proto3" json:"configMeta,omitempty"`
}

func (x *GetWorkerConfigRequest) Reset() {
	*x = GetWorkerConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkerConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerConfigRequest) ProtoMessage() {}

func (x *GetWorkerConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerConfigRequest.ProtoReflect.Descriptor instead.
func (*GetWorkerConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_message_proto_rawDescGZIP(), []int{1}
}

func (x *GetWorkerConfigRequest) GetConfigMeta() *ConfigMeta {
	if x != nil {
		return x.ConfigMeta
	}
	return nil
}

type UpdateWorkerConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigMeta *ConfigMeta `protobuf:"bytes,1,opt,name=configMeta,proto3" json:"configMeta,omitempty"`
	Config     *Config     `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *UpdateWorkerConfigRequest) Reset() {
	*x = UpdateWorkerConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWorkerConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkerConfigRequest) ProtoMessage() {}

func (x *UpdateWorkerConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkerConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkerConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_message_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateWorkerConfigRequest) GetConfigMeta() *ConfigMeta {
	if x != nil {
		return x.ConfigMeta
	}
	return nil
}

func (x *UpdateWorkerConfigRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sources    *_struct.Struct `protobuf:"bytes,1,opt,name=Sources,proto3" json:"Sources,omitempty"`
	Transforms *_struct.Struct `protobuf:"bytes,2,opt,name=Transforms,proto3" json:"Transforms,omitempty"`
	Sinks      *_struct.Struct `protobuf:"bytes,3,opt,name=Sinks,proto3" json:"Sinks,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_message_proto_rawDescGZIP(), []int{3}
}

func (x *Config) GetSources() *_struct.Struct {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *Config) GetTransforms() *_struct.Struct {
	if x != nil {
		return x.Transforms
	}
	return nil
}

func (x *Config) GetSinks() *_struct.Struct {
	if x != nil {
		return x.Sinks
	}
	return nil
}

type WorkerConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *_struct.Struct `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *WorkerConfigResponse) Reset() {
	*x = WorkerConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerConfigResponse) ProtoMessage() {}

func (x *WorkerConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerConfigResponse.ProtoReflect.Descriptor instead.
func (*WorkerConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_message_proto_rawDescGZIP(), []int{4}
}

func (x *WorkerConfigResponse) GetConfig() *_struct.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_config_message_proto protoreflect.FileDescriptor

var file_config_message_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x0a,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x2e, 0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x22, 0x4c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x0a, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x65,
	0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x77,
	0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x0a, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d,
	0x65, 0x74, 0x61, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x12,
	0x26, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0xa3, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x31, 0x0a, 0x07, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x07, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f,
	0x72, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x52, 0x0a, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x12, 0x2d,
	0x0a, 0x05, 0x53, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x05, 0x53, 0x69, 0x6e, 0x6b, 0x73, 0x22, 0x47, 0x0a,
	0x14, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x06,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_config_message_proto_rawDescOnce sync.Once
	file_config_message_proto_rawDescData = file_config_message_proto_rawDesc
)

func file_config_message_proto_rawDescGZIP() []byte {
	file_config_message_proto_rawDescOnce.Do(func() {
		file_config_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_message_proto_rawDescData)
	})
	return file_config_message_proto_rawDescData
}

var file_config_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_config_message_proto_goTypes = []interface{}{
	(*ConfigMeta)(nil),                // 0: config.ConfigMeta
	(*GetWorkerConfigRequest)(nil),    // 1: config.GetWorkerConfigRequest
	(*UpdateWorkerConfigRequest)(nil), // 2: config.UpdateWorkerConfigRequest
	(*Config)(nil),                    // 3: config.Config
	(*WorkerConfigResponse)(nil),      // 4: config.WorkerConfigResponse
	(*_struct.Struct)(nil),            // 5: google.protobuf.Struct
}
var file_config_message_proto_depIdxs = []int32{
	0, // 0: config.GetWorkerConfigRequest.configMeta:type_name -> config.ConfigMeta
	0, // 1: config.UpdateWorkerConfigRequest.configMeta:type_name -> config.ConfigMeta
	3, // 2: config.UpdateWorkerConfigRequest.config:type_name -> config.Config
	5, // 3: config.Config.Sources:type_name -> google.protobuf.Struct
	5, // 4: config.Config.Transforms:type_name -> google.protobuf.Struct
	5, // 5: config.Config.Sinks:type_name -> google.protobuf.Struct
	5, // 6: config.WorkerConfigResponse.config:type_name -> google.protobuf.Struct
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_config_message_proto_init() }
func file_config_message_proto_init() {
	if File_config_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkerConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWorkerConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_message_proto_goTypes,
		DependencyIndexes: file_config_message_proto_depIdxs,
		MessageInfos:      file_config_message_proto_msgTypes,
	}.Build()
	File_config_message_proto = out.File
	file_config_message_proto_rawDesc = nil
	file_config_message_proto_goTypes = nil
	file_config_message_proto_depIdxs = nil
}
